# Generated by Django 4.0.4 on 2022-04-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(verbose_name='date ordered')),
                ('ref', models.CharField(max_length=200)),
                ('starters', models.CharField(max_length=200)),
                ('mains', models.CharField(max_length=200)),
                ('deserts', models.CharField(max_length=200)),
            ],
        ),
    ]
