# Generated by Django 4.0.4 on 2022-04-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_taking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(verbose_name='date ordered')),
                ('ref', models.CharField(max_length=200)),
                ('table_number', models.IntegerField(choices=[(1, 'Table1'), (2, 'Table2'), (3, 'Table3'), (4, 'Table4'), (5, 'Table5'), (6, 'Table6'), (7, 'Table7')])),
                ('amount_of_guests', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ref',
        ),
    ]
