# Generated by Django 4.0.4 on 2022-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_taking', '0002_tables_remove_orders_date_remove_orders_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starters', models.CharField(max_length=200)),
                ('mains', models.CharField(max_length=200)),
                ('deserts', models.CharField(max_length=200)),
            ],
        ),
    ]
