# Generated by Django 4.0.4 on 2022-04-14 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_taking', '0003_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='amount_of_guests',
        ),
    ]
