# Generated by Django 4.0.4 on 2022-04-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_taking', '0004_remove_tables_amount_of_guests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='tables',
            new_name='Table',
        ),
    ]
