# Generated by Django 4.0.4 on 2022-04-15 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order_taking', '0005_rename_orders_order_rename_tables_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.AddField(
            model_name='order',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 4, 15, 12, 58, 38, 837861, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ref',
            field=models.CharField(default='n/a', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(choices=[(1, 'Table1'), (2, 'Table2'), (3, 'Table3'), (4, 'Table4'), (5, 'Table5'), (6, 'Table6'), (7, 'Table7'), (8, 'Table8'), (9, 'Table9'), (10, 'Table10'), (11, 'Table11'), (12, 'Table12'), (13, 'Table13'), (14, 'Table14'), (15, 'Table15'), (16, 'Table16'), (17, 'Table17')], default='1'),
        ),
        migrations.AddField(
            model_name='order',
            name='waiting_for_service',
            field=models.BooleanField(default=False),
        ),
    ]
