# Generated by Django 4.0.4 on 2022-04-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_taking', '0006_delete_course_delete_table_order_date_order_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deserts',
            field=models.CharField(choices=[('Bread & Butter Pudding', 'Bread & Butter Pudding'), ('Praline Chocolate Tart', 'Praline Chocolate Tart'), ('Lavender Panna Cotta', 'Lavender Panna Cotta'), ('Sticky Toffee Sundae', 'Sticky Toffee Sundae'), ('Clarckies Ice Cream', 'Clarckies Ice Cream'), ('Cheese Board', 'Cheese Board')], max_length=22),
        ),
        migrations.AlterField(
            model_name='order',
            name='mains',
            field=models.CharField(choices=[('Ribeye Steak', 'Ribeye Steak'), ('Sirloin Steak', 'Sirloin Steak'), ('Cheese Burger', 'Cheese Burger'), ('Black And Blue Burger', 'Black And Blue Burger'), ('Moving Mountain', 'Moving Mountain'), ('The Baxter', 'The Baxter'), ('Miss Daisy', 'Miss Daisy'), ('Beer Battered, Haddock', 'Beer Battered, Haddock'), ('Cod Fillet', 'Cod Fillet'), ('Perthshire Duck Breast', 'Perthshire Duck Breast'), ('Burgundy Beef', 'Burgundy Beef'), ('Mushroom & Tarragon Linguine', 'Mushroom & Tarragon Linguine'), ('Spiced Polenta', 'Spiced Polenta'), ('Mac and Cheese', 'Mac and Cheese')], max_length=28),
        ),
        migrations.AlterField(
            model_name='order',
            name='starters',
            field=models.CharField(choices=[('Soup of the day', 'Soup of the day'), ('Roasted red pepper hummus', 'Roasted red pepper hummus'), ('Charcuterie Board', 'Charcuterie Board'), ('Arbroath Smokie Risotto', 'Arbroath Smokie Risotto'), ('Hot Wings', 'Hot Wings'), ('Duck Leg & Fig Terrine', 'Duck Leg & Fig Terrine'), ('Beet Root Salad', 'Beet Root Salad')], max_length=25),
        ),
    ]
