# Generated by Django 4.0.4 on 2022-04-18 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_taking', '0007_alter_order_deserts_alter_order_mains_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
