# Generated by Django 4.0.4 on 2022-04-24 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_taking', '0008_alter_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_number', models.IntegerField(choices=[(1, 'Table1'), (2, 'Table2'), (3, 'Table3'), (4, 'Table4'), (5, 'Table5'), (6, 'Table6'), (7, 'Table7'), (8, 'Table8'), (9, 'Table9'), (10, 'Table10'), (11, 'Table11'), (12, 'Table12'), (13, 'Table13'), (14, 'Table14'), (15, 'Table15'), (16, 'Table16')], default='1')),
                ('Date', models.DateTimeField(default=datetime.datetime.now)),
                ('ref', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='ref',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(choices=[(1, 'Table1'), (2, 'Table2'), (3, 'Table3'), (4, 'Table4'), (5, 'Table5'), (6, 'Table6'), (7, 'Table7'), (8, 'Table8'), (9, 'Table9'), (10, 'Table10'), (11, 'Table11'), (12, 'Table12'), (13, 'Table13'), (14, 'Table14'), (15, 'Table15'), (16, 'Table16')], default='1'),
        ),
    ]
