# Generated by Django 4.0.4 on 2022-04-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_taking', '0009_table_alter_order_ref_alter_order_table_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='starter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starters', models.CharField(choices=[('Soup of the day', 'Soup of the day'), ('Roasted red pepper hummus', 'Roasted red pepper hummus'), ('Charcuterie Board', 'Charcuterie Board'), ('Arbroath Smokie Risotto', 'Arbroath Smokie Risotto'), ('Hot Wings', 'Hot Wings'), ('Duck Leg & Fig Terrine', 'Duck Leg & Fig Terrine'), ('Beet Root Salad', 'Beet Root Salad')], max_length=25)),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_taking.table')),
            ],
        ),
    ]
