# Generated by Django 4.0.4 on 2022-04-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_taking', '0010_starter'),
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mains', models.CharField(choices=[('Ribeye Steak', 'Ribeye Steak'), ('Sirloin Steak', 'Sirloin Steak'), ('Cheese Burger', 'Cheese Burger'), ('Black And Blue Burger', 'Black And Blue Burger'), ('Moving Mountain', 'Moving Mountain'), ('The Baxter', 'The Baxter'), ('Miss Daisy', 'Miss Daisy'), ('Beer Battered, Haddock', 'Beer Battered, Haddock'), ('Cod Fillet', 'Cod Fillet'), ('Perthshire Duck Breast', 'Perthshire Duck Breast'), ('Burgundy Beef', 'Burgundy Beef'), ('Mushroom & Tarragon Linguine', 'Mushroom & Tarragon Linguine'), ('Spiced Polenta', 'Spiced Polenta'), ('Mac and Cheese', 'Mac and Cheese')], max_length=28)),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_taking.table')),
            ],
        ),
        migrations.CreateModel(
            name='desert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deserts', models.CharField(choices=[('Bread & Butter Pudding', 'Bread & Butter Pudding'), ('Praline Chocolate Tart', 'Praline Chocolate Tart'), ('Lavender Panna Cotta', 'Lavender Panna Cotta'), ('Sticky Toffee Sundae', 'Sticky Toffee Sundae'), ('Clarckies Ice Cream', 'Clarckies Ice Cream'), ('Cheese Board', 'Cheese Board')], max_length=22)),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_taking.table')),
            ],
        ),
    ]
