# Generated by Django 4.0.4 on 2022-04-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_taking', '0011_main_desert'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deserts_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='mains_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='starter_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='deserts',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='mains',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='starters',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_taking.desert')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_taking.main')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_taking.starter')),
                ('table_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_taking.table')),
            ],
        ),
    ]
