# Generated by Django 4.0.4 on 2022-04-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_taking', '0012_order_deserts_ready_order_mains_ready_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
