# Generated by Django 4.0.4 on 2022-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_taking', '0014_remove_order_id_alter_order_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='served',
            field=models.BooleanField(default=False),
        ),
    ]
