# Generated by Django 4.0.4 on 2022-04-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_taking', '0015_order_served'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
